Update

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -15,7 +15,7 @@ if [ -d /m ]; then
     echo "Start to load modules from initrd ..."
     if [ -d /lib/modules/`uname -r` ]; then
       if [ ! -z "$KMODS" ]; then KMODS=$(echo $KMODS | sed 's/,/ /'); fi
-      for MODULE in $KMODS hid_apple hid applesmc input_polldev mbcache aufs overlay exportfs ext4 fat vfat fuse isofs nls_cp437 nls_iso8859-1 nls_utf8 reiserfs squashfs xfs f2fs jfs libata ahci libahci sata_sil24 pdc_adma sata_qstor sata_sx4 ata_piix sata_mv sata_nv sata_promise sata_sil sata_sis sata_svw sata_uli sata_via sata_vsc loop cdrom hid usbhid mptscsih mptspi mptsas tifm_core cb710 mmc_block mmc_core sdhci sdhci-pci wbsd tifm_sd cb710-mmc via-sdmmc vub300 sdhci-pltfm md_mod dm_mod dm_raid cryptd aes aes_generic aes_x86_64 aes_i586 dm_crypt cbc sha256_generic xts scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod usb-common usbcore ehci-hcd ehci-pci ohci-hcd uhci-hcd xhci-hcd usb-storage virtio virtio_blk virtio_pci virtio_net virtio_scsi; do
+      for MODULE in $KMODS hid-apple mac_hid applesmc input_polldev mbcache ntfs3 overlay exportfs ext4 fat vfat fuse isofs nls_cp437 nls_iso8859-1 nls_utf8 reiserfs squashfs xfs f2fs jfs libata ahci libahci sata_sil24 pdc_adma sata_qstor sata_sx4 ata_piix sata_mv sata_nv sata_promise sata_sil sata_sis sata_svw sata_uli sata_via sata_vsc loop cdrom hid usbhid mptscsih mptspi mptsas tifm_core cb710 mmc_block mmc_core sdhci sdhci-pci wbsd tifm_sd cb710-mmc via-sdmmc vub300 sdhci-pltfm md_mod dm_mod dm_raid cryptd aes aes_generic aes_x86_64 aes_i586 dm_crypt cbc sha256_generic xts scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod usb-common usbcore ehci-hcd ehci-pci ohci-hcd uhci-hcd xhci-hcd usb-storage virtio virtio_blk virtio_pci virtio_net virtio_scsi; do
         modprobe $MODULE >> /loadmodules.log 2>&1
         if [ "$?" != "0" ]; then rmmod $MODULE || true; fi
       done
@@ -69,6 +69,15 @@ UNION_FS_TYPE=`value unionfs`; [ $UNION_FS_TYPE ] || UNION_FS_TYPE='overlay'
 CHANGES_MOUNT=/memory/changes
 # kexec=/full/path/to/kernel/image to load secondary kernel. Same dir must have initrd.xz
 KEXEC=`value kexec`; [ $KEXEC ] || KEXEC=
+
+# generate hostname based on motherboard UUID if no hostname is given at all
+parse_passphrase() {
+    if echo $PASSPHRASE | grep '^#' >/dev/null 2>&1; then
+        HASHFUNC=$(echo $PASSPHRASE | cut -f2 -d#)
+        PASSPHRASE=$(cat /sys/devices/virtual/dmi/id/product_uuid | $HASHFUNC | cut -f1 -d' ')
+    fi
+}
+
 # Device Functions:
 detect_fs_type() { # where blkid does not understand that file system we need this hack
     echo "detect_fs_type $1"
@@ -112,10 +121,10 @@ for x in $dev; do
             continue
           fi
 	  if [ -z "$PASSPHRASE" ]; then echo "$x ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
-          echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
+          parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
           if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then 
 		echo "Failed, second try .."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p')
-   	  	echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
+   	  	parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
           fi
           if [ $? == 0 ]; then
               x="${x}_DEC"; ln -sf /dev/mapper/$x /dev/$x
@@ -132,11 +141,11 @@ for x in $dev; do
       else
           if [ -z "$PASSPHRASE" ]; then echo "$x ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
           if [ -z "$LUKS_HEAD" ]; then
-            echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen /dev/$x ${x}_DEC
+            parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen /dev/$x ${x}_DEC
           else
             echo -e "/dev/$x => '$LUKS_HEAD' .....\n\n"
             sh 
-            echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- --header=$LUKS_HEAD luksOpen /dev/$x ${x}_DEC
+            parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- --header=$LUKS_HEAD luksOpen /dev/$x ${x}_DEC
           fi
           if [ $? == 0 ]; then
               x="${x}_DEC"; ln -sf /dev/mapper/$x /dev/$x
@@ -333,11 +342,8 @@ mount -nt devtmpfs none /dev
 sleep 3 # devices settle down
 echo -e "done\ngenerate hostname ...\n"
 debug
-# generate hostname based on motherboard UUID if no hostname is given at all
-if echo $PASSPHRASE | grep '^#' >/dev/null 2>&1; then
-    HASHFUNC=$(echo $PASSPHRASE | cut -f2 -d#)
-    PASSPHRASE=$(cat /sys/devices/virtual/dmi/id/product_uuid | $HASHFUNC | cut -f1 -d' ')
-fi
+
+parse_passphrase
 
 [ -z "$HOSTNAME" ] && HOSTNAME=$(cat /sys/class/dmi/id/product_name | cut -f1 -d-)
 
@@ -470,11 +476,11 @@ if [ "$CHANGES" ]; then
               LODEV=$(losetup -f); losetup $LODEV $CIMAGE_FILE
               echo $i"sha512 $CIMAGE_FILE"
               if [ -z "$PASSPHRASE" ]; then echo "$CIMAGE_FILE ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
-              echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
+              parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
               if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then 
 		echo "Failed, second try .."
 		PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p')
-		echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
+		parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
 	      fi
               fsck_dat /dev/mapper/${IMG_FILE}.$$
               mount /dev/mapper/${IMG_FILE}.$$ $IMAGE_MOUNT_DIR 2>/dev/null && touch $IMAGE_MOUNT_DIR/._test1 2>/dev/null
@@ -484,11 +490,11 @@ if [ "$CHANGES" ]; then
                 LODEV=$(losetup -f); losetup $LODEV $CIMAGE_FILE
                 if [ -z "$PASSPHRASE" ]; then echo "$CIMAGE_FILE ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
                 if [ -z "$LUKS_HEAD" ]; then
-                    echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen $LODEV ${IMG_FILE}.$$
+                    parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen $LODEV ${IMG_FILE}.$$
                 else
                     echo "$RAW_DEV $LUKS_HEAD ....."
                     sh
-                    echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- --header=$LUKS_HEAD luksOpen $LODEV ${IMG_FILE}.$$
+                    parse_passphrase; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- --header=$LUKS_HEAD luksOpen $LODEV ${IMG_FILE}.$$
                 fi    
                 fsck_dat /dev/mapper/${IMG_FILE}.$$
                 mount /dev/mapper/${IMG_FILE}.$$ $IMAGE_MOUNT_DIR 2>/dev/null && touch $IMAGE_MOUNT_DIR/._test1 2>/dev/null
@@ -671,9 +677,9 @@ for x in `cat /tmp/modules`; do
     fi # will fail from the cdrom but does not matter
     NAME=`basename $x`; mkdir "/memory/images/$NAME"; LODEV=$(losetup -f); losetup $LODEV $x
     if blkid $LODEV 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
-       if [ ! -f "$PASSPHRASE" ]; then echo "$LODEV ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); echo $PASSPHRASE > $PASSPHRASE; fi
+       if [ ! -f "$PASSPHRASE" ]; then echo "$LODEV ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); parse_passphrase; echo $PASSPHRASE > $PASSPHRASE; fi
        cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC
-       if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then echo "Failed, second try .."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); echo $PASSPHRASE > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC; fi
+       if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then echo "Failed, second try .."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); parse_passphrase; echo $PASSPHRASE > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC; fi
        mount /dev/mapper/${NAME}_DEC /memory/images/$NAME
     else
        _MOUNT_MOD=1 # only mount current kernel ver
@@ -874,6 +880,19 @@ EOF
     chmod 1777 /union/tmp
     mkdir /union/mnt/live >/dev/null 2>&1
     debug
+    echo "Create /tmp/rc.local for this host. In /etc/rc.local you can detect and exec it"
+    if [ -f ${CHANGES_MOUNT_SRC}/${HOSTNAME}-rc.local ]; then
+        cp -a ${CHANGES_MOUNT_SRC}/${HOSTNAME}-rc.local /union/tmp/rc.local
+        chown root:root /union/tmp/rc.local
+        chmod 0600 /union/tmp/rc.local
+    fi
+    echo "Create /tmp/init-playbook.yaml for this host. In /etc/rc.local you can detect and run ansible-playbook on it to provision the host"
+    if [ -f ${CHANGES_MOUNT_SRC}/${HOSTNAME}-init-playbook.yaml ]; then
+        cp -a ${CHANGES_MOUNT_SRC}/${HOSTNAME}-init-playbook.yaml /union/tmp/init-playbook.yaml
+        chown root:root /union/tmp/init-playbook.yaml
+        chmod 0600 /union/tmp/init-playbook.yaml
+    fi
+
     pivot_root /union  /union/mnt/live
 # Execute commands in the new root eg. prepare, cleaning up before execting init.
     echo clean up systemd journal
