Overlay fs is enabled

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -13,7 +13,7 @@ if [ -d /m ]; then
     echo "Start to load modules from initrd ..."
     debug
     if [ -d /lib/modules/`uname -r` ]; then
-   	  for MODULE in mbcache aufs exportfs ext4 fat vfat fuse isofs nls_cp437 nls_iso8859-1 nls_utf8 reiserfs squashfs xfs f2fs jfs libata ahci libahci sata_sil24 pdc_adma sata_qstor sata_sx4 ata_piix sata_mv sata_nv sata_promise sata_sil sata_sis sata_svw sata_uli sata_via sata_vsc pata_ali pata_amd pata_artop pata_atiixp pata_atp867x pata_cmd64x pata_cs5520 pata_cs5530 pata_cs5535 pata_cs5536 pata_efar pata_hpt366 pata_hpt37x pata_it8213 pata_it821x pata_jmicron pata_marvell pata_netcell pata_ns87415 pata_oldpiix pata_pdc2027x pata_pdc202xx_old pata_rdc pata_sc1200 pata_sch pata_serverworks pata_sil680 pata_sis pata_triflex pata_via pata_isapnp pata_mpiix pata_ns87410 pata_opti pata_rz1000 ata_generic loop cdrom hid usbhid mptscsih mptspi mptsas tifm_core cb710 mmc_block mmc_core sdhci sdhci-pci wbsd tifm_sd cb710-mmc via-sdmmc vub300 sdhci-pltfm md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 xts scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod usb-common usbcore ehci-hcd ehci-pci ohci-hcd uhci-hcd xhci-hcd usb-storage virtio virtio_blk virtio_pci virtio_net; do
+   	  for MODULE in mbcache aufs overlay exportfs ext4 fat vfat fuse isofs nls_cp437 nls_iso8859-1 nls_utf8 reiserfs squashfs xfs f2fs jfs libata ahci libahci sata_sil24 pdc_adma sata_qstor sata_sx4 ata_piix sata_mv sata_nv sata_promise sata_sil sata_sis sata_svw sata_uli sata_via sata_vsc pata_ali pata_amd pata_artop pata_atiixp pata_atp867x pata_cmd64x pata_cs5520 pata_cs5530 pata_cs5535 pata_cs5536 pata_efar pata_hpt366 pata_hpt37x pata_it8213 pata_it821x pata_jmicron pata_marvell pata_netcell pata_ns87415 pata_oldpiix pata_pdc2027x pata_pdc202xx_old pata_rdc pata_sc1200 pata_sch pata_serverworks pata_sil680 pata_sis pata_triflex pata_via pata_isapnp pata_mpiix pata_ns87410 pata_opti pata_rz1000 ata_generic loop cdrom hid usbhid mptscsih mptspi mptsas tifm_core cb710 mmc_block mmc_core sdhci sdhci-pci wbsd tifm_sd cb710-mmc via-sdmmc vub300 sdhci-pltfm md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 xts scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod usb-common usbcore ehci-hcd ehci-pci ohci-hcd uhci-hcd xhci-hcd usb-storage virtio virtio_blk virtio_pci virtio_net; do
    modprobe $MODULE >/loadmodules.log 2>&1
 	    done
       echo "Done loading initial module '`uname -r`' from initrd"
@@ -44,7 +44,6 @@ IP=`value ip | cut -d: -f2`
 MOPT=`value mopt`; [ $MOPT ] || MOPT="noatime,nodiratime,suid,dev,exec,async"
 CHANGES=`value changes`
 RAMSIZE=`value ramsize`; [ $RAMSIZE ] || RAMSIZE=60%
-ZRAM=`value zram`; [ $ZRAM ] || ZRAM=
 ZRAMSIZE=`value zramsize`; [ $ZRAMSIZE ] || ZRAMSIZE=256M
 LOAD=`value load | sed 's/;/|/g'`; [ $LOAD ] || LOAD=""
 NOLOAD=`value noload | sed 's/;/|/g'`; [ $NOLOAD ] || NOLOAD=._null
@@ -70,7 +69,7 @@ cat > /etc/fstab << EOF
 # drive, filesystem or network share.
 
 # System mounts:
-aufs / aufs defaults 0 0
+# aufs / aufs defaults 0 0
 proc /proc proc defaults 0 0
 sysfs /sys sysfs defaults 0 0
 devtmpfs /dev devtmpfs defaults 0 0
@@ -115,7 +114,7 @@ for x in $dev; do
 			        mount -o loop $KMOD /opt/000-kernel  || echo "Can not mount $KMOD"
 			        if [ -d /opt/000-kernel/lib/modules/$KVER ]; then
 			          mount -o bind /opt/000-kernel/lib/modules /lib/modules
-			          for x in aufs md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod jfs ext2 ext4 ext3 squashfs isofs virtio virtio_blk virtio_pci virtio_net; do modprobe $x 2>/dev/null; done
+			          for x in aufs overlay md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod jfs ext2 ext4 ext3 squashfs isofs virtio virtio_blk virtio_pci virtio_net; do modprobe $x 2>/dev/null; done
 			          KMOD_DETECTED=y; echo "FOUND $KMOD"; echo "$KMOD" > /tmp/modules; break
 			        else
 			          umount /opt/000-kernel
@@ -135,7 +134,7 @@ for x in $dev; do
 			      mount -o loop $KMOD /opt/000-kernel || echo "=> Can not mount $KMOD <="
 			      if [ -d /opt/000-kernel/lib/modules/$KVER ]; then
 			        mount -o bind /opt/000-kernel/lib/modules /lib/modules
-			        for x in aufs md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod jfs ext2 ext4 ext3 squashfs isofs virtio virtio_blk virtio_pci virtio_net; do modprobe $x 2>/dev/null; done
+			        for x in aufs overlay md_mod dm_mod dm_raid dm_crypt cryptd cbc sha256_generic aes aes_generic aes_x86_64 aes_i586 scsi_mod scsi_transport_spi scsi_transport_sas sd_mod sr_mod jfs ext2 ext4 ext3 squashfs isofs virtio virtio_blk virtio_pci virtio_net; do modprobe $x 2>/dev/null; done
 			        KMOD_DETECTED=y; echo "FOUND $KMOD"; echo "$KMOD" > /tmp/modules; break
 			      else
 			        umount /opt/000-kernel; KMOD=
@@ -355,16 +354,6 @@ if [ $CHANGES ]; then
 				rmdir /memory/changes/mnt/* 2>/dev/null
 				rm -f /memory/changes/var/lock/subsys/* /var/run/laptop-mode-tools/*
 				for x in `find /memory/changes/var/run -name "*pid" 2>/dev/null`; do rm $x; done
-				if [ $CHNEXIT = EXIT ]; then
-					CHNEXIT=$CHNDEV/$LPTH; echo $CHNEXIT >/tmp/changes-exit
-					echo $i"[1;36m""changes will be saved only during reboot/shutdown""[0m"
-					#for x in `find /memory/changes -name ".wh.*"`; do cp -a --parents $x /var; done
-		#		    find /memory/changes  -name ".wh.*" | while IFS= read -r NAME; do cp -a --parents "$NAME" /var; done
-					umount /memory/changes; mount -nt tmpfs -o size=$RAMSIZE tmpfs /memory/changes
-					# need to fix busybox bug on 'cp -a' as it does not preserve perms on dirs:
-		#		    chown -R 1000:1000 /var/memory/changes/home/guest 2>/dev/null
-		#		    mv /var/memory/changes/* /memory/changes 2>/dev/null; CHANGES=memory
-				fi
 			fi
 		else
 			echo $i"changes not writable, using memory instead"; umount /memory/changes 2>/dev/null; fail_chn
@@ -376,11 +365,9 @@ else
      echo $i"changes cheatcode not found, using memory only"; fail_chn
 fi
 mkdir -p /memory/changes/mnt/live
-echo -e "done setup changes\nSetup aufs ...\n"
+echo -e "done setup changes\nSetup overlayfs ...\n"
 debug
 echo $i"creating live filesystem and inserting modules"
-mount -t aufs -o nowarn_perm,xino=/memory/xino/.aufs.xino,br:/memory/changes=rw aufs /union
-if [ $? -ne 0 ]; then echo -e "[31m""cant setup union (aufs) - read only filesystem?\nWhen you finish debugging press Ctrl+Alt+Del to reboot.""[0m"; sh; fi
 echo -e $i"done.\nFind modules ...\n"
 debug
 
@@ -455,7 +442,7 @@ if param copy2ram; then
     echo $i"copying data to RAM, this may take some time..."
     [ $RAMMOD ] && { egrep "$RAMMOD" /tmp/modules > /tmp/rammod; cpmod /tmp/rammod; } || cpmod /tmp/modules
 fi
-echo -e "Populate aufs with modules. If there is a .new file then use it if possible\n"
+echo -e "Populate overlay with modules. If there is a .new file then use it if possible\n"
 debug
 umount /lib/modules 2>/dev/null; umount /opt/000-kernel 2>/dev/null
 for x in `cat /tmp/modules`; do
@@ -473,7 +460,7 @@ for x in `cat /tmp/modules`; do
        if [ "$_M" == "1" ]; then mount $LODEV /memory/images/$NAME 2>/dev/null; fi
     fi
     if [ $? -eq 0 ]; then
-	  echo "  $m  $NAME"; mount -no remount,add:1:/memory/images/$NAME=rr aufs /union
+	  echo "  $m  $NAME"; LOWERDIR="$LOWERDIR:/memory/images/$NAME"
     else
 	echo $i"[1;36m""Cannot read $NAME - corrupted module?""[0m"; rmdir /memory/images/$NAME
         losetup -d $LODEV
@@ -482,12 +469,7 @@ done
 echo -e "done\nbind kernel module...\n"
 debug
 umount /lib/modules /opt/000-kernel 2>/dev/null
-mount -no bind /union/lib/modules /lib/modules 2>/dev/null
-if [ ! -d /union/lib/modules/${KVER}/kernel ]; then
-    mpath=`find /memory/images/ -name $KVER`
-    mkdir -p /union/lib/modules/$KVER >/dev/null 2>&1
-    mount -o bind $mpath /union/lib/modules/$KVER
-fi
+
 echo -e "done\n Add 'changes on exit' device/file/folder ...\n"
 debug
 if [ -e /tmp/changes-exit ]; then
@@ -499,9 +481,19 @@ if [ -e /tmp/changes-exit ]; then
     else
 		mount -o loop $CHNEXIT /memory/images/changes-exit
     fi
-    echo "  $m  changes-exit"; mount -no remount,add:1:/memory/images/changes-exit=ro+wh aufs /union
+# Not sure if it works with overlay
+    echo "  $m  changes-exit"; LOWERDIR="$LOWERDIR /memory/images/changes-exit" 
     echo $CHNEXIT/changes >>/tmp/modules
 fi
+
+LOWERDIR=`echo $LOWERDIR | sed 's/://'` # remove the first :
+
+echo "Mount overlay fs here at /union 'mount -t overlay overlay -o lowerdir=$LOWERDIR,upperdir=/memory/changes,workdir=/memory/workdir /union'"
+rm -rf /memory/changes/workdir >/dev/null 2>&1
+mkdir /memory/changes/workdir /memory/changes/rootdir
+mount -t overlay overlay -o lowerdir=$LOWERDIR,upperdir=/memory/changes/rootdir,workdir=/memory/changes/workdir /union
+if [ "$?" != 0 ]; then echo "Error mount overlay fs at /union start shell for debugging .."; /bin/sh ; exit 1; fi
+
 echo -e "done\nCopy /rootcopy folder...\n"
 if param norootcopy; then
     ROOTCOPY=none
@@ -539,7 +531,7 @@ fi
 cp -af /dev/console /union/dev
 rm -f /union/etc/mtab
 cat > /union/etc/mtab << EOF
-aufs / aufs rw 0 0
+#aufs / aufs rw 0 0
 proc /proc proc rw 0 0
 sysfs /sys sysfs rw 0 0
 devtmpfs /dev devtmpfs rw 0 0
@@ -619,19 +611,6 @@ EOF
        fi
     fi
     chmod 1777 /union/tmp
-    debug
-    if [ "$ZRAM" != '' ]; then
-     chroot /union /sbin/modprobe zram num_devices=1
-     echo $ZRAMSIZE > /sys/block/zram0/disksize
-     chroot /union /sbin/mkfs.jfs -q -s 1K /dev/zram0
-     chroot /union /sbin/modprobe jfs >/dev/null 2>&1
-     mkdir -p /memory/zram >/dev/null 2>&1
-     mount /union/dev/zram0  /memory/zram
-     cp -a /memory/changes/??* /memory/zram
-     mount -t aufs -o remount,prepend:/memory/zram=rw none /union
-     mount -t aufs -o remount,del:/memory/changes none /union
-     umount /memory/changes
-    fi
     debug
     pivot_root /union  /union/mnt/live
     #exec $CHROOT . /mnt/live/bin/init "$@" <dev/console >dev/console 2>&1
