Timeout to ask for pass

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -111,10 +111,11 @@ for x in $dev; do
             swapcrypt.sh $x
             continue
           fi
-          if [ -z "$PASSPHRASE" ]; then read -s -p "$x ..." PASSPHRASE; fi
+	  if [ -z "$PASSPHRASE" ]; then echo "$x ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
           echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
-          if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "$x ..." PASSPHRASE
-              echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
+          if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then 
+		echo "Failed, second try .."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p')
+   	  	echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
           fi
           if [ $? == 0 ]; then
               x="${x}_DEC"; ln -sf /dev/mapper/$x /dev/$x
@@ -129,7 +130,7 @@ for x in $dev; do
       if `ls /dev/mapper/${x}_DEC >/dev/null 2>&1`; then
           :
       else
-          if [ -z "$PASSPHRASE" ]; then read -s -p "******" PASSPHRASE ; fi
+          if [ -z "$PASSPHRASE" ]; then echo "$x ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
           if [ -z "$LUKS_HEAD" ]; then
             echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen /dev/$x ${x}_DEC
           else
@@ -468,16 +469,20 @@ if [ "$CHANGES" ]; then
             if blkid $CIMAGE_FILE 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
               LODEV=$(losetup -f); losetup $LODEV $CIMAGE_FILE
               echo $i"sha512 $CIMAGE_FILE"
-              if [ -z "$PASSPHRASE" ]; then read -s -p "..." PASSPHRASE; fi
+              if [ -z "$PASSPHRASE" ]; then echo "$CIMAGE_FILE ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
               echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
-              if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "..." PASSPHRASE; echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$; fi
+              if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then 
+		echo "Failed, second try .."
+		PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p')
+		echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${IMG_FILE}.$$
+	      fi
               fsck_dat /dev/mapper/${IMG_FILE}.$$
               mount /dev/mapper/${IMG_FILE}.$$ $IMAGE_MOUNT_DIR 2>/dev/null && touch $IMAGE_MOUNT_DIR/._test1 2>/dev/null
             elif [ ! -z "$RAW_DEV" ]; then
               _tmp=$(echo $CHANGES | cut -f1 -d/)
               if [ "$RAW_DEV" = "${_tmp}" ]; then
                 LODEV=$(losetup -f); losetup $LODEV $CIMAGE_FILE
-                if [ -z "$PASSPHRASE" ]; then read -s -p "*****" PASSPHRASE; fi
+                if [ -z "$PASSPHRASE" ]; then echo "$CIMAGE_FILE ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); fi
                 if [ -z "$LUKS_HEAD" ]; then
                     echo $PASSPHRASE | /usr/bin/cryptsetup --key-file=- plainOpen $LODEV ${IMG_FILE}.$$
                 else
@@ -666,9 +671,9 @@ for x in `cat /tmp/modules`; do
     fi # will fail from the cdrom but does not matter
     NAME=`basename $x`; mkdir "/memory/images/$NAME"; LODEV=$(losetup -f); losetup $LODEV $x
     if blkid $LODEV 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
-       if [ ! -f "$PASSPHRASE" ]; then read -s -p "Enter pass for $NAME: " PASSPHRASE; echo $PASSPHRASE > $PASSPHRASE; fi
+       if [ ! -f "$PASSPHRASE" ]; then echo "$LODEV ..."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); echo $PASSPHRASE > $PASSPHRASE; fi
        cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC
-       if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "Enter pass for $NAME: " PASSPHRASE; echo $PASSPHRASE > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC; fi
+       if [ $? != 0 ] && [ ! -z "$PASSPHRASE" ]; then echo "Failed, second try .."; PASSPHRASE=$(timeout 30 sh -c 'read -s p && echo $p'); echo $PASSPHRASE > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC; fi
        mount /dev/mapper/${NAME}_DEC /memory/images/$NAME
     else
        _MOUNT_MOD=1 # only mount current kernel ver
