Update trying to use gocrypt or encfs as upperdir for overlay with fail
[18904.011268] overlayfs: upper fs does not support tmpfile.
[18904.011695] overlayfs: upper fs does not support RENAME_WHITEOUT.

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -488,6 +488,15 @@ if [ "$CHANGES" ]; then
         fi    
     else
         CHANGES_MOUNT_SRC=/mnt/$DEV/$LPTH
+# This does not work with overlayfs,  upper fs does not support tmpfile.
+# upper fs does not support RENAME_WHITEOUT. Looks like FUSE does not support it yet? Same for gocryptfs and encfs
+        if [ -d ${CHANGES_MOUNT_SRC}.gocryptfs ]; then
+            /usr/bin/gocryptfs ${CHANGES_MOUNT_SRC}.gocryptfs ${CHANGES_MOUNT_SRC}
+            if [ $? -eq 0 ]; then
+                echo "error, spawn shell to recover manually. Press Ctrl + d to continue"
+                /bin/sh
+            fi
+        fi
         CHANGES_DEV=$DEV
         echo "locate or create success CHANGES_MOUNT_SRC=$CHANGES_MOUNT_SRC CHANGES_DEV=$CHANGES_DEV"
     fi
@@ -716,7 +725,7 @@ if [ "$UNION_FS_TYPE" = 'aufs' ]; then
     mount -t aufs -o br=${CHANGES_MOUNT}/rootdir=rw:${LOWERDIR} none /union
 else
     echo "Going to mount command 'mount -t overlay overlay -o lowerdir=$LOWERDIR,upperdir=${CHANGES_MOUNT}/rootdir,workdir=${CHANGES_MOUNT}/workdir /union'"
-    echo "overlay option metacopy=on is buggy? Disable it for now. We got lots of error 'overlayfs: failed to look up (.profile) for ino (-5)' ..."
+    #echo "overlay option metacopy=on is buggy? Disable it for now. We got lots of error 'overlayfs: failed to look up (.profile) for ino (-5)' ..."
     mount -t overlay overlay -o lowerdir=$LOWERDIR,upperdir=${CHANGES_MOUNT}/rootdir,workdir=${CHANGES_MOUNT}/workdir /union
 fi    
 if [ "$?" != 0 ]; then echo "Error mount $UNION_FS_TYPE fs at /union start shell for debugging .."; /bin/sh ; exit 1; fi
