Allow second time to ask passphrase

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -84,7 +84,7 @@ for x in $dev; do
 		else
 			if [ ! -f $PASSPHRASE ]; then read -s -p "Enter passphrase to open disk $x" PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; fi
 			cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC
-			if [ $? != 0 ]; then echo "Failed, second try .."; /usr/bin/cryptsetup luksOpen $LODEV ${NAME}_DEC; fi
+			if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "Enter passphrase to open disk $x" PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/$x ${x}_DEC ; fi
 			if [ $? == 0 ]; then
 				x="${x}_DEC"; ln -sf /dev/mapper/$x /dev/$x
 				fsck_dat /dev/$x
@@ -151,6 +151,7 @@ if [ -z "`egrep -o " noswap( |\$)" /etc/cmdline`" -a -e /tmp/devices ]; then
 	for x in `grep 'TYPE="swap"' /tmp/devices | cut -d: -f1`; do echo "$x none swap sw,pri=1 0 0" >>/etc/fstab; done
   grep -v 'TYPE="crypto_LUKS"' /etc/fstab > /etc/fstab.new; mv /etc/fstab.new /etc/fstab
 fi } # end fstab
+
 mount_device() {
 fs=`blkid /dev/$1 | egrep -o ' TYPE=[^ ]+' | cut -d'"' -f2`
 if [ "$fs" ]; then
@@ -207,6 +208,7 @@ elif [ $fs = rei ]; then
 else
     echo $i"detected unsupported fs - skipping fsck"
 fi } # end fsck_dat
+
 cpmod() { NUM=`grep -c '.' $1`
 for x in `cat $1`; do
     echo -en "[1;33m""  ($NUM modules left)  \r""[0m"; let NUM=NUM-1; NAME=`basename $x`
@@ -220,7 +222,8 @@ for x in `cat $1`; do
     fi
 done
 echo -en "                       \r"; } # end cpmod
-echo "start portetus init script - modified by stevek version v1.9"
+
+echo "start portetus init script - modified by stevek version v1.10"
 # Make all drivers available: stevek move it first so we have module
 debug
 mount -nt devtmpfs none /dev
@@ -325,10 +328,10 @@ if [ $CHANGES ]; then
 		  else
 		  	if blkid /mnt/$DEV/$LPTH 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
 		  	  losetup /dev/loop2 /mnt/$DEV/$LPTH
-		  	  echo $i"found encrypted .dat container"
+		  	  echo $i"found encrypted image container"
 		  	  if [ ! -f $PASSPHRASE ]; then read -s -p "Enter pass for encrypted .dat: " PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; fi
 		  	  cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/loop2 crypt
-		  	  if [ $? != 0 ]; then echo "Failed, second try .."; /usr/bin/cryptsetup luksOpen $LODEV ${NAME}_DEC; fi
+		  	  if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "Enter pass for encrypted .dat: " PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen /dev/loop2 crypt; fi
 		  	  fsck_dat /dev/mapper/crypt
 		  	  mount /dev/mapper/crypt /memory/changes 2>/dev/null && touch /memory/changes/._test1 2>/dev/null
 		  	else
@@ -459,7 +462,7 @@ for x in `cat /tmp/modules`; do
     if blkid $LODEV 2>/dev/null | cut -d" " -f3- | grep -q _LUKS; then
 	   if [ ! -f $PASSPHRASE ]; then read -s -p "Enter pass for $NAME: " PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; fi
 	   cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC
-       if [ $? != 0 ]; then echo "Failed, second try .."; /usr/bin/cryptsetup luksOpen $LODEV ${NAME}_DEC; fi
+       if [ $? != 0 ]; then echo "Failed, second try .."; read -s -p "Enter pass for $NAME: " PASSPHRASE; echo $PASSPHRASE | md5sum | cut -f1 -d' ' > $PASSPHRASE; cat $PASSPHRASE | /usr/bin/cryptsetup --key-file=- luksOpen $LODEV ${NAME}_DEC; fi
        mount /dev/mapper/${NAME}_DEC /memory/images/$NAME
     else
        _M=1 # only mount current kernel ver
