Try to not re-run generate device
The hp laptop has strange issues with running ftab repeatedly

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -66,7 +66,7 @@ PASSPHRASE_FILE=`value passfile`; [ "$PASSPHRASE_FILE" ] || PASSPHRASE_FILE=
 RAW_DEV=`value raw`; [ "$RAW_DEV" ] || RAW_DEV=`value r`
 FACTORYRESET=`value reset`; [ $FACTORYRESET ] || FACTORYRESET=`value factoryreset`; [ $FACTORYRESET ] || FACTORYRESET='0'
 # FACTORYRESET values: 1 - reset but keep home, 2 reset with backup - 3 reset everything, no backup, 4 reset mod 999,
-# -1 reset base image to .old and keep home 
+# -1 reset base image to .old and keep home
 KVER=`uname -r`
 KPATH=`value kpath`; [ $KPATH ] || KPATH=
 KMOD_DETECTED=
@@ -222,9 +222,9 @@ for x in $dev; do
   if [ "$fs" = "ntfs" ]; then
     echo "detect ntfs going to mount with -o $MOPT"
     $MOUNT_NTFS_CMD /dev/$x /mnt/$mountdir
-    if [ $? != 0 ]; then 
-        echo "mount error"; sed -i "/$x /d" /etc/fstab; rmdir /mnt/$x; 
-    else 
+    if [ $? != 0 ]; then
+        echo "mount error"; sed -i "/$x /d" /etc/fstab; rmdir /mnt/$x;
+    else
         if [ "${_x_is_usb}" = "yes" ]; then sleep 2; fi
     fi
     for _PATH in /mnt/${x}/${FROM}/${OSDIR}/base /mnt/${mountdir}/${FROM} /mnt/${mountdir}/${KPATH}; do
@@ -248,18 +248,18 @@ for x in $dev; do
       fi
     done
   else
-    mount -n /mnt/$mountdir 2>/dev/null 
-    if [ $? != 0 ]; then   
-       modprobe $fs 2>/dev/null 
-       mount -n /mnt/$mountdir 2>/dev/null 
+    mount -n /mnt/$mountdir 2>/dev/null
+    if [ $? != 0 ]; then
+       modprobe $fs 2>/dev/null
+       mount -n /mnt/$mountdir 2>/dev/null
        if [ $? != 0 ]; then
          sed -i "/$x /d" /etc/fstab; rmdir /mnt/$mountdir
-       else 
+       else
          if [ "${_x_is_usb}" = "yes" ]; then sleep 2; fi
        fi
-    else 
-        if [ "${_x_is_usb}" = "yes" ]; then sleep 2; fi   
-    fi 
+    else
+        if [ "${_x_is_usb}" = "yes" ]; then sleep 2; fi
+    fi
     for _PATH in /mnt/${mountdir}/${FROM}/${OSDIR}/base /mnt/${mountdir}/${FROM} /mnt/${mountdir}/${KPATH}; do
       if [ "$KMOD_DETECTED" == "y" ]; then break; fi
       KMODS=`find ${_PATH}/000-*.[xglz]zm 2>/dev/null`
@@ -451,9 +451,9 @@ if param pause; then
     /bin/sh
 fi
 fstab
-echo "Re-generate again as fstab will mount kernel module and load extra devices in."
-debug
-generate_devices
+# echo "Re-generate again as fstab will mount kernel module and load extra devices in."
+# debug
+# generate_devices
 echo -e "done\ncheck KEXEC ...\n"
 debug
 rm -f /etc/mtab ; ln -sf /proc/mounts /etc/mtab
@@ -482,9 +482,9 @@ if [ ! -z "$KEXEC" ]; then
             echo exec kernel now
             /usr/bin/kexec -e
         else
-            echo some error with kexec. hit enter to continue old kernel; read _junk    
-        fi    
-    fi    
+            echo some error with kexec. hit enter to continue old kernel; read _junk
+        fi
+    fi
 fi
 
 echo -e "done\n$i searching for $SGN file ...\n"
@@ -529,25 +529,25 @@ echo -e $i"use current porteus base image $CURRENT_IMAGE_FILE"
 
 echo -e $i"done.\nCheck update image porteus-update-$(value os)-${arch}.squashfs ...\n"
 debug
-if [ "$FACTORYRESET" = "-1" ] && [ -f "${CURRENT_IMAGE_FILE}.old" ]; then 
+if [ "$FACTORYRESET" = "-1" ] && [ -f "${CURRENT_IMAGE_FILE}.old" ]; then
     echo "FACTORYRESET is -1 and ${CURRENT_IMAGE_FILE}.old exists. Will base image reset to that file "
-    rm "${CURRENT_IMAGE_FILE}.new" || true 
+    rm "${CURRENT_IMAGE_FILE}.new" || true
     mv "${CURRENT_IMAGE_FILE}.old" "${CURRENT_IMAGE_FILE}"
     FACTORYRESET='1'
 fi
-if [ -f "${CURRENT_IMAGE_FILE}.new" ]; then 
+if [ -f "${CURRENT_IMAGE_FILE}.new" ]; then
   echo "Found ${CURRENT_IMAGE_FILE}.new"
   if [ "$FACTORYRESET" = "0" ]; then echo "Set FACTORYRESET=1"; FACTORYRESET='1'; fi
   echo "Skip UPDATE_IMAGE_FILE"; UPDATE_IMAGE_FILE=""
-else 
+else
   UPDATE_IMAGE_FILE=$(find /mnt/*/ -maxdepth 1 -name "porteus-update-$(value os)-${arch}.squashfs")
-fi 
+fi
 if [ ! -z "$UPDATE_IMAGE_FILE" ]; then
   echo "Found UPDATE_IMAGE_FILE $UPDATE_IMAGE_FILE"
   if [ $(stat -c %Y $UPDATE_IMAGE_FILE) -gt $(stat -c %Y $CURRENT_IMAGE_FILE) ]; then
     echo -e $i"move $UPDATE_IMAGE_FILE to $CURRENT_IMAGE_FILE"
     cp -a $UPDATE_IMAGE_FILE $CURRENT_IMAGE_FILE
-    mv $UPDATE_IMAGE_FILE ${UPDATE_IMAGE_FILE}.old 
+    mv $UPDATE_IMAGE_FILE ${UPDATE_IMAGE_FILE}.old
   else
     echo "current image newer or equal than update image."
   fi
